Dev
closup/process-xbrl pull request #158
Opened 2024-12-10 19:00 UTC by sarraha786

Before the 13th of January, Marc wants the CLOSUP website to be able to handle City of Brea (attached) template and make sure the empty template, conversion process, iXBRL viewer has no issues. I believe there are no major issues on the `dev` branch and want to see if we can merge it into `main` before this deadline.

The CLOSUP website has been updated so that instead of being embedded, you click on the 'Get Started' button and it opens a new tab with the `main` branch deployment on Heroku.

The following conversion works on `dev` branch
[City of Brea, CA.xlsx](https://github.com/user-attachments/files/18169006/City.of.Brea.CA.xlsx)

What we want to review (on different browsers too) @kwheelan @sarraha786 

- [x] UI/UX is right (following conversion)
- [ ] Downloading button, uploading, converting, deleting files, opening iXBRL viewer all work
     - KW: Yes, but download does not work for all versions of Chrome.
- [ ] Make sure CLOSUP website loads the tool properly
    - KW: Links to `main` deployment but this will work once this PR is merged.
- [x] Make sure the empty ACFR template is up to date

### Changes

 - Closes #132 
 - Closes #134 
 - Closes #140 
 - Closes #161 
 - Removes submodules and sets `arelle` and `ixbrl-viewer` to be static releases.
 - Fixes an issue with negatives in the reconciliation table without breaking XBRL parsing of negative numbers or dollar signs

### Remaining issues

- #133 
- #139 
- #163
- #164
- #165
- #166

2024-12-31 22:07 UTC, kwheelan commented
@lucakato 

I'll continue reviewing, but on first pass, there are a few major issues. When I add the Clayton files (Word and Excel) or even just the Brea file, it takes me to the right page, but then the "Download File" button doesn't do anything. Then clicking on "Click to View in Browser" doesn't fully load the interactive viewer. See screenshot:

![Screenshot 2024-12-31 at 4 58 40 PM](https://github.com/user-attachments/assets/82d648d8-d2c1-4350-b979-0236aa2d23ee)

Usually when it gets stuck loading like that, it's because of an error in the XBRL.

Tested with Brea Excel and this Clayton file: 
[Clayton Excel.xlsx](https://github.com/user-attachments/files/18283800/Clayton.Excel.xlsx)

2025-01-12 17:14 UTC, lucakato commented
@kwheelan The download button works for me on Safari and Chrome. Is it a popup block for you? Fixing the viewer.

2025-01-12 18:52 UTC, lucakato commented
@kwheelan Please check again, with the latest iXBRL viewer ver it should work.

2025-01-12 20:21 UTC, kwheelan commented
@lucakato 

Ixbrl viewer works for me now. 

The issue with both `main` and `dev` is that they are set to download the most recent release of both `ixbrl-viewer` and `arelle`, which can break our code. 

I will add this to the review, but we should instead set ixbrl-viewer and arelle to a static version. At one point I had fixed the versions to 
```
arelle_version = "2.17.5"
ixbrl_viewer_version = "1.4.9"
```
But if it now works with the most recent release of both, let's just set the versions to those release numbers.

I would suggest doing this in the `.gitmodules` file, which will automatically download the correct version as submodules for Heroku. I see that you added and changed the versions in `requirements.txt` in e41b99a2865e14cb2eb7eb571cd7aa901947797b and 84b742b33151e955aff5118cdc0b6d4cf7a498de. Having `arrelle-release` in there will download the most recent release of the package. I *think* you should be able to delete that from the requirements file completely. Just make sure you manually clone and initialize the same versions of Arelle and ixbrl-viewer in your personal environment by running `git submodule update --init --recursive`. Let me know if you have any issues with that.

In Chrome, the download still doesn't work for me (and I don't have any 3rd party pop-up blockers, just the most recent version of Chrome). Safari gives me an warning popup but allows me to download. Basically #139 from November is still unfixed. 

When I upload multiple files, they still don't get reordered according to the list order when I drag and drop. (Ie. #133 is still an issue).

A new issue: 
There are some extra empty lines that render where they shouldn't, especially before the 'Notes' and in the reconciliation tables:

![Screenshot 2025-01-12 at 3 13 11 PM](https://github.com/user-attachments/assets/ae248b71-ee26-42b3-874b-9fb23f5126de)
![Screenshot 2025-01-12 at 3 13 28 PM](https://github.com/user-attachments/assets/8ce94e49-5e16-4356-adf6-0de04a4ef80f)

I think we probably don't want a "Note:" to render at all unless there is some text in the note, but that's something to double-check with Marc.

2025-01-12 20:26 UTC, kwheelan commented
@lucakato 

Most of the above comments are issues with `main` as well, so I'll finish a quick code review this afternoon and go ahead and merge even without all of these issues resolved.

2025-01-12 21:38 UTC, lucakato commented
@kwheelan 
where are you getting the following versions?
```
arelle_version = "2.17.5"
ixbrl_viewer_version = "1.4.9"
```

The versions I have installed in my venv are:
```
Arelle Version: 2.36.0
iXBRL viewer version: 1.4.44
```
but when I create my iXBRL viewer in `xbrl_processing.py` I am using the 1.4.48 as follows:
```
viewer_url = "https://cdn.jsdelivr.net/npm/ixbrl-viewer@1.4.48/iXBRLViewerPlugin/viewer/dist/ixbrlviewer.js"
```

2025-01-12 21:58 UTC, kwheelan requested changes
@lucakato 

Before I merge, please revert changes to the Cell class and the `table.html` template file that cause XBRL parsing errors for negative values and values with dollar signs (see my comments). 

The other edits and my comments from before are less essential, so I'll create issues for them. Just let me know when you fix the cell error and I will merge into `main`.

2025-01-12 21:58 UTC, kwheelan commented on app/templates/xbrl/table.html
> +    </td>
@lucakato You need to revert this change. For properly formatted XBRL, only the value (absolute value) can be inside the tag. So putting the formatted value will break the XBRL interpretation for anything that's negative or anything with a dollar sign. All of those need to be outside the tag (that's why we have the `prefix()` and `suffix()` functions in the `Cell` class). 

Notice how the viewer doesn't work for negatives:
<img width="1137" alt="Screenshot 2025-01-12 at 4 27 39 PM" src="https://github.com/user-attachments/assets/a7e24666-fc33-4635-9b82-9690ed5c49e7" />

or for the first row with dollar signs:
<img width="1142" alt="Screenshot 2025-01-12 at 4 28 48 PM" src="https://github.com/user-attachments/assets/2bb6af31-f6ef-4cc9-a871-12db24b1fa85" />

2025-01-12 21:58 UTC, kwheelan commented on app/models/cell.py
> +        return self.formatted_value()
@lucakato You may need to revert this change as well -- see my comment on `templates/xbrl/table.html`

2025-01-12 21:58 UTC, kwheelan commented on app/models/cell.py
> +
@lucakato You shouldn't need this function -- see my comment on `templates/xbrl/table.html`

2025-01-12 21:58 UTC, kwheelan commented on app/models/dimension.py
> +        self._domain = "DefaultDomain"
@lucakato What's the idea behind these defaults? As I can tell from the xbrl download, these just create 2 unused contexts. If they are used, a few notes:
- They should be just "Default" for both domain and axis because the words "Domain" and "Axis" are added automatically. Now they get called as "DefaultAxisAxis" and "DefaultDomainDomain"
- Not all contexts have domains, so I really don't think we need a default domain (unless someone else from CLOSUP had an xbrl-specific reason to include these?)

2025-01-12 21:58 UTC, kwheelan commented on app/models/net_position.py
> +            print(f"Debug: First few rows:\n{rows.head()}")
@lucakato Do we need to keep all these debug print statement?

2025-01-12 21:58 UTC, kwheelan commented on app/models/net_position.py
> +                if xbrl_tag == "Choose from drop-down -->":
@lucakato You also might want to skip rows where xbrl_tag is empty

2025-01-12 21:58 UTC, kwheelan commented on app/models/net_position.py
> +            print("Debug: No cells were processed")
@lucakato Need to keep the print statements? I'd suggest switching all of these to error statements that only print if there was an issue to avoid clogging the terminal.

2025-01-12 21:58 UTC, kwheelan commented on app/models/reconcilation_table.py
> +        print(f"Debug: First few rows of final DataFrame:\n{self._df.head()}")
@lucakato Again, I'd delete these and create an optional error statement

2025-01-12 22:45 UTC, kwheelan commented
> @kwheelan where are you getting the following versions?
> 
> ```
> arelle_version = "2.17.5"
> ixbrl_viewer_version = "1.4.9"
> ```
> 
> The versions I have installed in my venv are:
> 
> ```
> Arelle Version: 2.36.0
> iXBRL viewer version: 1.4.44
> ```
> 
> but when I create my iXBRL viewer in `xbrl_processing.py` I am using the 1.4.48 as follows:
> 
> ```
> viewer_url = "https://cdn.jsdelivr.net/npm/ixbrl-viewer@1.4.48/iXBRLViewerPlugin/viewer/dist/ixbrlviewer.js"
> ```

From a very old version of the code: https://github.com/closup/process-xbrl/commit/05358d4dce51864d1718d979012aa3c84cde7b81#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L145. I maintained those versions by deploying the Heroku branch from my CLI and initializing the submodules from there. ([The main branch Heroku deployment](https://xbrl-converter-22f50351e04c.herokuapp.com/upload/complete?session_id=9f160af3-5961-4ccd-beec-932491781ed1) should still work because I think it's running these old versions). 

Notice that the repos in the dependencies folder are older commits: https://github.com/closup/process-xbrl/tree/main/dependencies. Looks like ixbrl-viewer got updated in commit 112004266f9b86f38380399185af1d9eb81469ff  but arelle is still a version from 11 months ago). 

Your new version of arelle is probably because you downloaded the arelle package using pip rather than cloning the repo. If this automatically downloads ixbrl-viewer, maybe this is a better strategy than having submodules at all? I will mess with in in the branch I just created for #163

2025-01-12 23:02 UTC, kwheelan commented
@lucakato I fixed the versioning issue -- your strategy of just downloading the python packages of `arelle` and `ixbrl-viewer` is much cleaner than dealing with the submodules. I just deleted all the submodule stuff and set the versions for the two packages in `requirements.txt`. We eventually make sure we specify versions for all the package requirements in that file. (See issue #163).

For this PR, let's just revert the cell.py error and merge. I made issues for everything else.

2025-01-12 23:04 UTC, lucakato commented
@kwheelan I'm working on reverting to using `show_value()`. I believe the main reason I did this was because when we were testing it out with a bunch of new templates, there was an issue where some negative values did not have a bracket around it. Like the image below, it's not clickable, and the value (918,156) is not appearing in brackets as expected
![image](https://github.com/user-attachments/assets/ba200671-5996-4d8f-9c5a-bee3e3138fe5)
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/a2ec7a53-1252-48c7-9b90-7e125a2c73d5" />

If I revert I believe the `fact-value` on iXBRL viewer should work. But it doesn't handle cases such as the above.

2025-01-12 23:23 UTC, kwheelan commented
> @kwheelan I reverted to using `show_value()` on branch #158. I believe the main reason I did this was because when we were testing it out with a bunch of new templates, there was an issue where some negative values did not have a bracket around it. Like for the table below it's not clickable, and the value (918,156) is not appearing in brackets as expected. So I made changes but didn't notice it affected `fact-value`.
> 
> I have a new branch #158. Also here's the TX file (not super up to date since Ram did not edit Sarrah's abs latest file [Pittsburg.Excel Final.xlsx](https://github.com/user-attachments/files/18391504/Pittsburg.Excel.Final.xlsx)
> 
> If I revert I believe the `fact-value` on iXBRL viewer should work. But it doesn't handle cases such as the above.

Got it. The issue is because the reconciliation tables aren't taggable.

Both issues should be fixed if you adjust this section of `app/templates/xbrl/table.html`.
```
    <td id="{{ cell.id }}" class="{{ cell.td_class() }}">
        {% if cell.needs_ix_tag() %}
        {{ cell.prefix() }}<ix:nonFraction contextRef="{{ cell.context_ref() }}" name="{{ cell.xbrl_tag() }}" unitRef="USD" id="{{ cell.id }}" decimals="0" format="{{ cell.format() }}" {% if cell.sign() == 'negative' %} sign="-" {% endif %}>{{ cell.show_value() }}</ix:nonFraction>{{ cell.suffix() }}
        {% else %}
            {{ cell.show_value() }}
        {% endif %}
```

so that the last part (which deals with the reconciliation cells) is instead: 
```
        {% else %}
            {{ cell.formatted_value() }}
        {% endif %}
```
but keep the reverted {{ cell.show_value() }} in line 18.

2025-01-12 23:31 UTC, lucakato commented
> > @kwheelan I reverted to using `show_value()` on branch #158. I believe the main reason I did this was because when we were testing it out with a bunch of new templates, there was an issue where some negative values did not have a bracket around it. Like for the table below it's not clickable, and the value (918,156) is not appearing in brackets as expected. So I made changes but didn't notice it affected `fact-value`.
> > I have a new branch #158. Also here's the TX file (not super up to date since Ram did not edit Sarrah's abs latest file [Pittsburg.Excel Final.xlsx](https://github.com/user-attachments/files/18391504/Pittsburg.Excel.Final.xlsx)
> > If I revert I believe the `fact-value` on iXBRL viewer should work. But it doesn't handle cases such as the above.
> 
> Got it. The issue is because the reconciliation tables aren't taggable.
> 
> Both issues should be fixed if you adjust this section of `app/templates/xbrl/table.html`.
> 
> ```
>     <td id="{{ cell.id }}" class="{{ cell.td_class() }}">
>         {% if cell.needs_ix_tag() %}
>         {{ cell.prefix() }}<ix:nonFraction contextRef="{{ cell.context_ref() }}" name="{{ cell.xbrl_tag() }}" unitRef="USD" id="{{ cell.id }}" decimals="0" format="{{ cell.format() }}" {% if cell.sign() == 'negative' %} sign="-" {% endif %}>{{ cell.show_value() }}</ix:nonFraction>{{ cell.suffix() }}
>         {% else %}
>             {{ cell.show_value() }}
>         {% endif %}
> ```
> 
> so that the last part (which deals with the reconciliation cells) is instead:
> 
> ```
>         {% else %}
>             {{ cell.formatted_value() }}
>         {% endif %}
> ```
> 
> but keep the reverted {{ cell.show_value() }} in line 18.

thanks that worked and I pushed to #158-dev-review branch. I'll merge it with dev

2025-01-13 00:19 UTC, kwheelan commented on app/models/dimension.py
> +        self._domain = "DefaultDomain"
#165

2025-01-13 00:20 UTC, kwheelan commented on app/models/net_position.py
> +            print(f"Debug: First few rows:\n{rows.head()}")
Moved to #166

2025-01-13 00:21 UTC, kwheelan commented on app/models/cell.py
> +        return self.formatted_value()
Resolved in #168

2025-01-13 00:21 UTC, kwheelan commented on app/models/cell.py
> +
Resolved in #168

2025-01-13 00:21 UTC, kwheelan commented on app/models/net_position.py
> +                if xbrl_tag == "Choose from drop-down -->":
See #164

2025-01-13 00:22 UTC, kwheelan commented on app/models/net_position.py
> +            print("Debug: No cells were processed")
#166

2025-01-13 00:22 UTC, kwheelan commented on app/models/reconcilation_table.py
> +        print(f"Debug: First few rows of final DataFrame:\n{self._df.head()}")
#166

2025-01-13 00:25 UTC, kwheelan approved these changes

2025-01-13 00:33 UTC, merged